### ISSUE TITLE
查询单词释义为空时，不应该添加到记忆库

### ISSUE THREAD

**Issue by Funnyang** [cdpath/anki_tools#1]
你好，非常感谢你写了这个脚本。让我可以以非常低成本的方式进行修改，初步使用发现空的释义也会添加到记忆库。这是由于你对` $definition`的检查放在了`look_up`函数，而在 `main` 函数没有再次检查，具体为什么还需要在 `main` 中检查，你可以参考 [why-does-exit-1-not-exit-the-script](https://unix.stackexchange.com/questions/172541/why-does-exit-1-not-exit-the-script/172543)。我进行了一点修改 fix 这个问题。代码如下：

```
main()
{
    local definition=$(look_up $safe_entry)
    ## $definition 应在当前 shell 判断，函数中是在 subshell 执行，因此实际上不能终止程序
    if [[ -z "$definition" ]]; then
        exit 1
    else
        payload=$(gen_post_data "$definition")
        res=$(curl -sX POST -d "$payload" "localhost:8765")
        check_result "$res" "$definition"
    fi
}
```

因为我做了一些中文适配可自己用，所以就不提 pull requests 了，你可以自行修改。

感谢你的付出！

**Comment by cdpath** [comment]
Thanks for pointing it out. Fixed it.
